unclassified:         
                          # THis file and fields are just for info purpose such that later to send email or notify in slack etc.
  location:

    url: "http://localhost:8080/"      # This is the jenkins url i am telling to jenkins

    adminAddress: "muhammadashir2004@gmail.com"   # This is my email I am tellig to Jenkins


jenkins:        

  clouds:                           # jenkins cloud configuration

    - kubernetes:         # cofigruing kubernetes agent

        name: "kubernetes"        

        serverUrl: "https://kubernetes.default"       # api server url

        namespace: "jenkins"                   # The agent pod will be deployed in this namesapce

        jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"     # jenkins server ip resolve with codeDNS

        jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"  # When the agent pod is deployed, it consists of jnlp container
                                          # When an Agent Pod starts its jnlp container connects to this address on Port 50000 to register itself with Jenkins.
                                          # without it the agent pod would never become online
                                          # in my setup helm is creating the service jenkins-agent automatically
                                          
                                          # The Jenkins controller creates agent pod, The jnlp container inside that Agent Pod connects back to the Jenkins 
                                          # Controller through the jenkins-agent Service at this address

        containerCapStr: "10"         # THis is the max pod agent is allowed to create

        connectTimeout: 5       # jenkins waits for 5 sec until establish connection with api server then retries

        readTimeout: 15           # jenkins waits for 15 seconds for kubernetes to return data

        maxRequestsPerHostStr: "32"   # jenkins can make max 32 simultaneous http req to the api server

        useJenkinsProxy: false        # As i am running jenkins, agent, and deployment in the same cluster therefore no proxy is needed

        skipTlsVerify: true        # for now, i have disabled the tls verification