apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc
  labels:
    app.kubernetes.io/name: jenkins
    jenkins-jenkins-config: "true"    # THIS IS THE KEY!! THE JENKINS HELM CONTAINS A SIDEDCAR CALLED 'kiwigrid/k8s-sidecar'
data:                                 # THIS SIDECAR COTINUOUSLY WATCHES k8s FOR CONFIGMAP WITH THIS LABEL AND IF FIND, IT COPIES
                                      # EVERY YAML INSIDE IT INTO THE /var/jenkins_home/casc_configs
  system.yaml: |
{{ .Files.Get "files/jcasc/system.yaml" | indent 4 }}

  security.yaml: |
{{ .Files.Get "files/jcasc/security.yaml" | indent 4 }}

  tools.yaml: |
{{ .Files.Get "files/jcasc/tools.yaml" | indent 4 }}

  credentials.yaml: |
{{ .Files.Get "files/jcasc/credentials.yaml" | indent 4 }}

  shared-library.yaml: |
{{ .Files.Get "files/jcasc/shared-library.yaml" | indent 4 }}

  appearance.yaml: |
{{ .Files.Get "files/jcasc/appearance.yaml" | indent 4 }}

  plugin-config.yaml: |
{{ .Files.Get "files/jcasc/plugin-config.yaml" | indent 4 }}
